---
- name: Create /etc/hosts file on managed nodes 
  hosts: srv 
  become: true 
  tasks: 
  
    - name: Create hosts file using j2 template 
      template: 
        src: /home/hayden/ansible/templates/srv/hostsfile.j2
        dest: /etc/hosts
