---
- name: Set the login banner for cluster 
  hosts: srv 
  become: true 
  gather_facts: true

  tasks:

    - name: Modify the login banner located in /etc/motd on the homelab devices
      template: 
       src:  /home/hayden/ansible/templates/srv/motd.j2
       dest: /etc/motd
       force: yes
