- name: Configure IOS with a .cfg template for netdevops 
  hosts: cisco 
  become: true 
  tasks: 

    - name: Pull current running configuration
      cisco.ios.ios_command:
        commands: show running-config
      register: current_config

    - name: Save backup configuration on control node 
      ansible.builtin.copy:
        content: "{{ current_config.stdout[0] }}"
        dest: "/home/hayden/ansible/backups/{{ inventory_hostname }}_{{ lookup('pipe', 'date +%F') }}.cfg"
        mode: '2775'

    - name: Push entire config file and save
      cisco.ios.ios_config:
        config: "{{ lookup('ansible.builtin.template', '/home/hayden/ansible/templates/net/cisco/' + inventory_hostname + '.j2') }}"
        save_when: changed
