---
- name: Juniper base configuration
  hosts: juniper
  gather_facts: false

  tasks:
    - name: Juniper base config
      juniper.device.config:
        load: "set"
        lines:
          - "delete interfaces ge-0/0/1 unit 0 family ethernet-switching"
          - "set interfaces ge-0/0/1 unit 0 family inet dhcp"
