---
- name: Enable services to be persistent through reboot 
  hosts: homelab
  become: true 

  tasks:

    - name: Enable services and ensure they are persistent through reboot
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: 
        - firewalld
        - sshd 
        - cron.service

