---
- name: Install baseline software
  hosts: homelab
  become: true 

  tasks:
    - name: Install a list of packages
      apt:
        pkg: "{{ item }}"
      loop:   
        - firewalld
        - lvm2
        - autofs 
        - vim 
        - docker 
        - podman 
        - git  
    
