---
- name: Install baseline software
  hosts: homelab
  become: true 

  tasks:
    - name: Install baseline software for Debian systems
      apt:
        pkg: "{{ item }}"
      loop:   
        - firewalld
        - lvm2
        - autofs 
        - vim 
        - docker 
        - podman 
        - git 
      when: ansible_distribution == 'Debian' 

    - name: Install baseline software for Redhat systems
      yum:
        pkg: "{{ item }}"
      loop:   
        - firewalld
        - lvm2
        - autofs 
        - vim 
        - docker 
        - podman 
        - git 
      when: ansible_distribution == 'RedHat'    
