---
- name: Set the login banner for cluster 
  hosts: homelab 
  become: true 
  gather_facts: true

  tasks:

    - name: Modify the login banner located in /etc/motd on the homelab devices
      template: 
       src:  /Users/hayden/development/ansible/templates/motd.j2
       dest: /etc/motd
       force: yes
