---


prod_software:
  - firewalld 
  - autofs
  - lvm2 
  - vim 
  - ansible 
  - git 
  - docker
  - podman
  - python3

prod_services: 
  - firewalld 
  - cron.service
  - autofs

disks: 
  - sda
  - sdb


ansible_python_interpreter: /usr/bin/python3.11 
